// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAorXPy7TZLna3Wk_cFNyav7olLQCiHIAo',
    appId: '1:882797735498:web:0440e42653f4003b8140b3',
    messagingSenderId: '882797735498',
    projectId: 'obligation-tracker-11add',
    authDomain: 'obligation-tracker-11add.firebaseapp.com',
    storageBucket: 'obligation-tracker-11add.firebasestorage.app',
    measurementId: 'G-18H8J46Y65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpIl2N81tJ3wxnl7xhvUZ6phS7QF1hikI',
    appId: '1:882797735498:android:72a817f6e3b4347f8140b3',
    messagingSenderId: '882797735498',
    projectId: 'obligation-tracker-11add',
    storageBucket: 'obligation-tracker-11add.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0EGfKrjHxBQ_uvMc5YFejle-hQkAV4ZU',
    appId: '1:882797735498:ios:d18fb0dddd9df0018140b3',
    messagingSenderId: '882797735498',
    projectId: 'obligation-tracker-11add',
    storageBucket: 'obligation-tracker-11add.firebasestorage.app',
    iosBundleId: 'com.example.obligationTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0EGfKrjHxBQ_uvMc5YFejle-hQkAV4ZU',
    appId: '1:882797735498:ios:d18fb0dddd9df0018140b3',
    messagingSenderId: '882797735498',
    projectId: 'obligation-tracker-11add',
    storageBucket: 'obligation-tracker-11add.firebasestorage.app',
    iosBundleId: 'com.example.obligationTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAorXPy7TZLna3Wk_cFNyav7olLQCiHIAo',
    appId: '1:882797735498:web:25d82a0b1a7b6c708140b3',
    messagingSenderId: '882797735498',
    projectId: 'obligation-tracker-11add',
    authDomain: 'obligation-tracker-11add.firebaseapp.com',
    storageBucket: 'obligation-tracker-11add.firebasestorage.app',
    measurementId: 'G-QLSL3004VR',
  );
}
